on:
  push:
    branches:
      - master



jobs:
  build:
    runs_on: ubuntu_latest


    steps:
      - uses: actions/checkout@v3
      - name: "Login to docker hub"
        run: docker login --username radwakhonany --password dckr_pat_1elRKlVo86ycoV0nWdSGSjbrySU

     
     
